### ISSUE TITLE
Harbor App (Appimage) cannot load config

### ISSUE THREAD

**Issue by FrantaNautilus** [av/harbor#64]
After making a clean install of `harbor` CLI (`harbor doctor` shows everything OK), I tried the Harbor App via AppImage. No AppImage wrapper was used, only `chmod +x HarborApp.AppImage` and `./HarborApp.AppImage`.
The problem is only the `Profiles` tab which outputs an error "Unexpected error loading configuration".
![Screenshot from 2024-10-23 14-21-22](https://github.com/user-attachments/assets/46bfeb55-4bf1-4078-924b-04da02f31338)
Other tabs are unaffected.

**Comment by av** [comment]
Thank you so much for another report!

Unfortunately I can't reproduce it right away, so we'll have to debug

Just released v0.2.12 comes with a couple of things that should help:
- `harbor doctor` now prints location of the Harbor Home, it should be present in the App in the "CLI" page, could you please check that the value there matches what you see when running the `harbor doctor` in the terminal?
- Fixed one edge-case related to a deletion of a currently selected config profile. The error state looks slightly different compared to your screenshot, but worth trying it out with the new app build

Other than that - I have a suspicion that it might be related to either:
- AppImage sandboxing which isn't kicking in on my system and is available by default on yours (Fedora SilverBlue, right?)
- AppImage not bundling correct dependencies (unlikely, but not impossible)

**Comment by FrantaNautilus** [comment]
As before thank you for quick update of `harbor`, however the problem persists. I followed the troubleshooting you have suggested and here are the results.

Harbor App doctor (the values match between App and CLI):
✔ Docker is installed and running
✔ Docker Compose (v2) is installed
✔ Harbor home: /var/home/user/.harbor
✔ Default profile exists and is readable
✔ Current profile (.env) exists and is readable
✔ CLI is linked
✔ NVIDIA Container Toolkit is installed

CLI:
14:57:09 [INFO] ✔ Docker is installed and running
14:57:09 [INFO] ✔ Docker Compose (v2) is installed
14:57:09 [INFO] ✔ Harbor home: /var/home/user/.harbor
14:57:09 [INFO] ✔ Default profile exists and is readable
14:57:09 [INFO] ✔ Current profile (.env) exists and is readable
14:57:09 [INFO] ✔ CLI is linked
14:57:09 [INFO] ✔ NVIDIA Container Toolkit is installed

I tried to disable sandboxing for the AppImage by running it with `--no-sandbox` flag, however the problem persists (the output remains the same).

I have also tried to make clean manual install instead of automated. And the error remains.

What I found are some fixed issues concerning Fedora Silverblue and broken support of AppImage. For example [https://github.com/fedora-silverblue/issue-tracker/issues/589](https://github.com/fedora-silverblue/issue-tracker/issues/589). Yet none of the problems reported there seem to be connected to this one. I plan to upgrade to Fedora Silverblue 41 soon (probably next weekend), so I can test if there is anything different.

Also, can I ask if you have any plans for Flatpak release? Flatpak in my experience has fewer (user side) problems than AppImage.

**Comment by av** [comment]
Yeah, nothing in these looks suspicious in any way. The `--no-sandbox` seems to be related to the Electron apps (Harbor runs with Tauri). Granted the homedir location, could you please try running it with: `--filesystem=/var`? Very thin chance, but still

I'm certain that this happens because of some sort of discrepancy in the FS access permissions between the systems with a very short possible fix. As another attempt - could you please try running it via AppImage launcher? 

> any plans for Flatpak release?

Unfortunately in Harbor's case, the Flatpak would be just a [repackaged `.deb`](https://v2.tauri.app/distribute/flatpak/#prerequisites), I'm not 100% it'll work on Silverblue (just learned about immutable FS), It looks like you won't be able to use the provided `rpm` due to exactly the same reason

**Comment by av** [comment]
I've added a "guess" fix to https://github.com/av/harbor/releases/tag/v0.2.14 with an explicit permission to read/write to the User's home folder (previously was under the wildcard). Also a thin chance that it fixes the problem for you, but please try running the AppImage from that release

**Comment by FrantaNautilus** [comment]
Thank you for incredibly fast update, I updated CLI and the App. Nevertheless, the problem remains the same in version 0.2.14 with or without `--filesystem=/var` flag.
I noticed that the button create profile is clickable despite the error. The profile creation dialog opens and upon clicking create profile the screen flashes and dialog closes, simultaneously the following error is produced in command line:
```
** (harbor-app:364900): WARNING **: 19:10:21.768: atk-bridge: get_device_events_reply: unknown signature
```
Hopefully I will be able to install the `rpm` version on my test PC tomorrow (running the same Fedora Silverblue 40, installation via layering of the package).

**Comment by av** [comment]
No worries!

I'll try to find some time to test the AppImage in a VM during my next chunk of Harbor time (next weekend or a weekend after that)

Thanks for sticking it out through the early versions

**Comment by FrantaNautilus** [comment]
Sorry for taking long with a reply, I am still having issues with upgrading to Fedora 41 (Nvidia drivers), so for now I tried to install the Harbor App into Fedora toolbox (which is should have access to the system as if I installed on non-immutable Fedora). The App is installed without any errors, but the problem remains the same as with the AppImage. Now the only thing that these different installations have in common is that home directory is under `/var` and security policy of Fedora.

**Comment by av** [comment]
I was working on a somewhat related feature (that'll eventually also let me test the app in the Fedora easier) and found out a possible culprit.

I think that the desktop entry in Fedore will run in a custom shell without the `$PATH` modification added by Harbor. Theoretically, when starting the App from a terminal directly, it should inherit the correct env and have access to Harbor's executable.

So, could you please try launching the app from the terminal instead of the desktop entry and let me know if it makes the app functioning?

```bash
# App's binary is named "harbor-app" and should be made available
# on the host during install
which harbor-app
# Should be something like: /usr/bin/harbor-app

# If not found - look into the .desktop entry for the app:
cat /usr/share/applications/Harbor.desktop 

# Launch the app binary directly:
harbor-app
```

I'm currently trying to find any workarounds, but still curious to know if this was the reason in your instance.

Thanks!

**Comment by FrantaNautilus** [comment]
Thank you for coming back to my issue. I am sorry I did not reply immediately, however I am still figuring out how to properly install RPM package on the immutable Fedora Silverblue (without breaking anything else). I updated to the latest version of `harbor` (CLI and App Appimage) and the issue persists. As for the debugging steps you suggest for the RPM, I tried to install RPM through Distrobox which shares the system configuration partially, yet it cannot detect Docker. I will have to layer the RPM directly.

**Comment by av** [comment]
Absolutely no worries! 

I'm hoping to get my hands on testing this next weekend. Recent Harbor release included `webtop` service with the Harbor App pre-installed, could be used as a workaround until we get it to work natively

**Comment by av** [comment]
@lor-ai could you please share outputs of `harbor doctor` and `harbor info` on your system and also outline how are you launching the app?

**Comment by lor-ai** [comment]
user@computer: $ harbor doctor
13:20:50 [INFO] Running Harbor Doctor...
13:20:50 [INFO] ✔ Docker is installed and running
13:20:50 [INFO] ✔ Docker Compose (v2) is installed
13:20:50 [INFO] ✔ Docker Compose (v2) version is newer than 2.23.1
13:20:50 [INFO] ✔ Harbor home: /home/asa/.harbor
13:20:50 [INFO] ✔ Default profile exists and is readable
13:20:50 [INFO] ✔ Current profile (.env) exists and is readable
13:20:50 [INFO] ✔ CLI is linked
13:20:50 [INFO] ✔ NVIDIA GPU is available
13:20:50 [INFO] ✔ NVIDIA Container Toolkit is installed
13:20:50 [WARN] ✘ ROCm in not installed. AMD GPU support may not work.
13:20:50 [INFO] Harbor Doctor checks completed successfully.
user@computer: $harbor info
Harbor CLI version: 0.3.5
==========================
13:20:55 [WARN] Harbor has no active services.
==========================
Client: Docker Engine - Community
 Version:    28.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 28.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.0-19-generic
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.62GiB
 Name: ubu24
 ID: 04a87faf-f9e5-480a-b34a-07d97da49f45
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false

I'll note that I've installed it one various entirely fresh systems, in each of the methods for the CLI (pipx, npm, manual, unsafe) and tried both appimage (packed and unpacked), and the .deb package, launched both manually (i.e harbor-app) and via gnome (harbor.desktop) as both root and $USER. 

I've also tried manually changing the $HARBOR_HOME location in the .env and .local/bin/harbor files. And updating FUSE, etc. And launching it with --filesystem=/var and --filesystem=/$HOME, /usr, /root , just to see if its would work. And changing my bashrc  to point to the /.harbor folder in both root and $USER. 

I haven't tried Ubuntu22.04 as I was having driver compatibility issues with my system, although I have had luck on that OS when running in WSL2 on the Windows side. Do you have a dockerfile for harbor with a GUI, that I could docker.sock from into the host system? Or if you see a way to fix the app on the host, that'd be amazing.

Sorry for the long infoblast, I'm not very technical, so I'm not sure it what helps lol, but I really want to get this going as this project and the app is one of the main reasons I'm switching to Ubuntu as my main OS. 

Thanks again.

**Comment by lor-ai** [comment]
Copy. I probably should have mentioned that it seems like the app can communicate with the CLI. It's able to launch containers and compose commands. But it can't read the profiles it seems and that page just reads "Unexpected error loading configuration". with the same flash that OP was describing when you hit the + button. Not sure if that gives you any insight into what might be conflicting? The .deb package is the same deal. Is there anywhere I could check in the unpack appimage that might give some insight? Would not being able to see the profiles folder or the .envs inside keep that pages gui boxes from appearing?

**Comment by av** [comment]
Aha, that clarifies things, thank you!

Yes, it's most likely a file access permission issue then. It's either on Tauri (framework for Harbor app) or OS side. The "CLI" page in the App also prints `doctor` output, including location of Harbor home folder. It's that location that isn't resolved correctly by the app.

Here's the code in the app that read profiles:
https://github.com/av/harbor/blob/main/app/src/config/useHarborConfig.ts#L19

And here're Tauri FS permissions:
https://github.com/av/harbor/blob/main/app/src-tauri/capabilities/default.json#L58

Now that I see it I wonder if `*/**` was a typo in the GitHub issues 🤔

**Comment by av** [comment]
Added mentioned possible workaround in [v0.3.6](https://github.com/av/harbor/releases/tag/v0.3.6) - if you'll have a chance to test, please let me know

**Comment by elijahdev0** [comment]
I'm on Fedora and having the same issue. Tried the newest release. the appimage is just blank white, the rpm version in the latest version works but 2 issues. 

1: When pressing the button on a service like openwebui that's supposed to redirect me to my browser nothing happens.
2: Unexpected error loading configuration is still happening

**Comment by av** [comment]
The Profiles failure is reproducible on current main: the app can locate Harbor home, but Tauri rejects reads below a dot-prefixed `.harbor` directory with `forbidden path .../.harbor/profiles`. PR #269 fixes that filesystem-scope setting. I verified the same running app goes from “Unexpected error loading configuration” to showing Current/Default and successfully creating a new profile, and repeated the check with the optimized release binary.

I also checked the later Fedora reports separately. The published v0.5.13 AppImage still starts with a blank window here on Fedora 43 and logs `Could not create default EGL display: EGL_BAD_PARAMETER`. Its bundle contains older Wayland/XCB libraries; this matches the Tauri bundler issue at https://github.com/tauri-apps/tauri/issues/15976. Removing those libraries from an extracted test copy stops the EGL error, but did not yet produce a usable UI, so I am not claiming the AppImage symptom is fixed by #269. The reported service Open button is a separate path (`harbor url` followed by `xdg-open`) and is not changed by the Profiles fix. If it still fails with a current RPM, please include the service name and the terminal outputs of `harbor url <service>` and `xdg-open "$(harbor url <service>)"` so that failure can be isolated.
